const palabras = [
	new Palabra(0, "A", "Empieza por A:", "Estructura de datos en JavaScript que permite almacenar y manipular una colección de elementos, como números o cadenas, en una sola variable.", "Array"),
  	new Palabra(1, "B", "Empieza por B:", "Parte de una página HTML donde se encuentra el contenido principal que se muestra en el navegador.", "Body"),
	new Palabra(2, "C", "Empieza por C:", "Lenguaje utilizado para dar estilo y diseño a las páginas web, controlando la presentación de elementos HTML.", "CSS"),
	new Palabra(3, "D", "Empieza por D:", "Etiqueta HTML que se usa para agrupar contenido o elementos con el fin de organizar mejor la estructura de la página.", "Div"),
	new Palabra(4, "E", "Empieza por E:", "Acción que ocurre en el navegador o en un elemento HTML, como un clic, y que puede ser capturada y gestionada con JavaScript.", "Evento"),
	new Palabra(5, "F", "Contiene la F:", "Propiedad de CSS que se utiliza para posicionar un elemento en relación con el borde izquierdo de su contenedor cuando se usa position relativo, absoluto o fijo.", "Left"),
	new Palabra(6, "G", "Empieza por G:", "Sistema en CSS que permite organizar elementos en filas y columnas, creando estructuras de diseño flexibles.", "Grid"),
	new Palabra(7, "H", "Empieza por H:", "Parte del documento HTML donde se incluyen metadatos, como el título de la página o enlaces a archivos CSS y JavaScript.", "Head"),
	new Palabra(8, "I", "Empieza por I:", "Atributo HTML que asigna un identificador único a un elemento, útil para manipularlo con JavaScript o CSS.", "Id"),
	new Palabra(9, "J", "Empieza por J:", "Lenguaje de programación que permite hacer que las páginas web sean interactivas, respondiendo a acciones del usuario.", "Javascript"),
	new Palabra(10, "K", "Empieza por K", "Evento de JavaScript que se activa cuando una tecla es presionada en el teclado.", "Keydown"),
  	new Palabra(11, "L", "Contiene la L:", "Tipo de dato que puede tener solo dos valores: true o false, utilizado en condiciones y comparaciones lógicas.", "Boolean"),
	new Palabra(12, "M", "Empieza por M:", "Propiedad en CSS que define el espacio exterior alrededor de un elemento, separándolo de otros.", "Margin"),
	new Palabra(13, "N", "Empieza por N:", "Objeto global en JavaScript que representa un valor vacío o inexistente.", "Null"),
	new Palabra(14, "O", "Empieza por O:", "Con la O: Propiedad de CSS que especifica cómo manejar el contenido que desborda el área de un elemento.", "Overflow"),
	new Palabra(15, "P", "Empieza por P:", "Propiedad de CSS utilizada para definir el espacio interior de un elemento, creando espacio entre el contenido y los bordes.", "Padding"),
	new Palabra(16, "Q", "Empieza por Q:", "Copia exacta de un texto que se inserta en una publicación de contenido propio", "Quote"),
	new Palabra(17, "R", "Empieza por R:", " Método JavaScript se usa para redondear un número al entero más cercano", "Round"),
	new Palabra(18, "S", "Empieza por S:", "Propiedad CSS se usa para establecer la sombra de un texto", "Shadow"),
	new Palabra(19, "T", "Empieza por T:", "Atributo HTML utilizado en formularios para especificar el tipo de entrada que debe recibir un campo, como texto, contraseña, correo, etc.", "Type"),
	new Palabra(20, "U", "Empieza por U:", "Elemento HTML que define una lista no ordenada, usualmente representada por viñetas.", "Ul"),
	new Palabra(21, "V", "Empieza por V:", "Propiedad de CSS que define si un elemento es visible u oculto, permitiendo su espacio en la página.", "Visibility"),
	new Palabra(22, "W", "Empieza por W:", "Propiedad de CSS utilizada para establecer el ancho de un elemento.", "Width"),
	new Palabra(23, "X", "Empieza por X:", "Asociación de empresas tecnológicas de Castellón", "Xarxatec"),
	new Palabra(24, "Y", "Contiene la Y:", "Un superset de JavaScript que añade tipos estáticos al lenguaje. Permite detectar errores de tipo en tiempo de desarrollo y proporciona herramientas de autocompletado más avanzadas en editores de código.", "Typescript"),
	new Palabra(25, "Z", "Empieza por Z:", "Lugar donde se desarrolla la formación de Xarxatec Activa.", "Puzzle"),
];
